#!/bin/bash

dir="test"

if [ -d "$dir" ]; then
    echo "dir exists"
    file="$dir/myfile.txt"
    if [ -f "$file" ]; then
        echo "file exists in dir"
    else
        echo "file doesnot exist"
    fi
else
    echo "dir doesnot exist"
fi 